# Generated by Django 5.2 on 2025-05-08 09:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BookSeries",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Book",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("url", models.URLField(max_length=1000, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("rating", models.FloatField(blank=True, null=True)),
                ("reviews_count", models.IntegerField(blank=True, null=True)),
                ("best_seller_ranks", models.JSONField(blank=True, null=True)),
                ("popular_reviews", models.JSONField(blank=True, null=True)),
                (
                    "parse_status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("not parsed", "Not Parsed"),
                            ("in progress", "In Progress"),
                            ("completed", "Completed"),
                            ("error", "Error"),
                        ],
                        max_length=255,
                        null=True,
                    ),
                ),
                ("parsed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "series",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="books",
                        to="core.bookseries",
                    ),
                ),
            ],
        ),
    ]
