# Generated by Django 5.2 on 2025-05-08 10:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="language",
            field=models.CharField(
                blank=True,
                choices=[
                    ("en", "English"),
                    ("de", "German"),
                    ("fr", "French"),
                    ("it", "Italian"),
                    ("es", "Spanish"),
                    ("pt", "Portuguese"),
                    ("mx", "Mexican"),
                    ("nl", "Dutch"),
                    ("ru", "Russian"),
                    ("ja", "Japanese"),
                ],
                max_length=255,
                null=True,
            ),
        ),
    ]
