services:
  web:
    container_name: parser
    image: amazon_parser
    build: ../
    # command: >
    #     sh -c "uv run amazon_parser/manage.py migrate &&
    #           uv run amazon_parser/manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"
    environment:
      - DEBUG=1
    volumes:
      - ./data/db:/app/amazon_parser/db
      - ./data/pages:/app/amazon_parser/data
  